# Generated by Django 5.1.6 on 2025-02-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('Rentals', 'Rentals'), ('Sales', 'Sales')], max_length=50)),
                ('built_up_area', models.FloatField()),
                ('carpet_area', models.FloatField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('construction_status', models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under construction', 'Under construction')], max_length=50)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('security_deposit', models.CharField(choices=[('None', 'None'), ('1 month', '1 month'), ('2 month', '2 month'), ('Custom', 'Custom')], max_length=50)),
                ('category', models.CharField(choices=[('Apartments', 'Apartments'), ('Duplexes', 'Duplexes'), ('Houses', 'Houses'), ('Villas', 'Villas')], max_length=50)),
                ('bhk_type', models.CharField(choices=[('1 RK', '1 RK'), ('1 BHK', '1 BHK'), ('1.5 BHK', '1.5 BHK'), ('2 BHK', '2 BHK'), ('3+ BHK', '3+ BHK')], max_length=50)),
                ('furnishing_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('enable_street_view', models.BooleanField(default=False)),
                ('street_view_angle', models.IntegerField(blank=True, help_text='Value from 0 to 360', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='property_pdfs/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('virtual_tour', models.TextField(blank=True, null=True)),
                ('age_of_property', models.CharField(blank=True, max_length=50, null=True)),
                ('facing_direction', models.CharField(blank=True, choices=[('North', 'North'), ('East', 'East'), ('West', 'West'), ('South', 'South')], max_length=10, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('balconies', models.PositiveIntegerField(blank=True, null=True)),
                ('floors_no', models.CharField(blank=True, max_length=20, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('basement', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
