# Generated by Django 5.1.6 on 2025-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property',
            field=models.CharField(default='Default Value', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
