# Generated by Django 5.1.6 on 2025-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_property_property_alter_property_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property',
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
