# Generated by Django 5.1.6 on 2025-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_property_longitude_remove_property_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
