# Generated by Django 5.1.6 on 2025-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_property_monthly_rent_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_up_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
