# Generated by Django 5.1.6 on 2025-02-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_property_latitude_alter_property_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
