# Generated by Django 5.1.6 on 2025-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_property_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
