# Generated by Django 5.1.6 on 2025-02-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_property_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pdf_file',
        ),
    ]
