# Generated by Django 5.1.6 on 2025-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_property_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='enable_street_view',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street_view_angle',
        ),
        migrations.AddField(
            model_name='property',
            name='googlemap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
