# Generated by Django 5.1.6 on 2025-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_property_enable_street_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
