# Generated by Django 5.1.6 on 2025-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_property_pdf_file_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial Property')], max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=255)),
                ('square_feet', models.PositiveIntegerField()),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('EMD', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
