# Generated by Django 5.1.6 on 2025-03-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auction_alter_property_listing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='property_type',
        ),
        migrations.AddField(
            model_name='auction',
            name='bhk_type',
            field=models.CharField(blank=True, choices=[('1 RK', '1 RK'), ('1 BHK', '1 BHK'), ('1.5 BHK', '1.5 BHK'), ('2 BHK', '2 BHK'), ('3+ BHK', '3+ BHK')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Apartments', 'Apartments'), ('Duplexes', 'Duplexes'), ('Houses', 'Houses'), ('Villas', 'Villas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
