# Generated by Django 5.1.6 on 2025-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_auction_property_type_auction_bhk_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
