# Generated by Django 5.1.6 on 2025-03-07 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.reigstermodel'),
        ),
    ]
