# Generated by Django 5.1.6 on 2025-03-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_property_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='userid',
        ),
        migrations.AddField(
            model_name='auction',
            name='token_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
