# Generated by Django 5.1.6 on 2025-03-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_property_userid_auction_token_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('orderstatus', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('propertyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.auction')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reigstermodel')),
            ],
        ),
    ]
