# Generated by Django 5.1.6 on 2025-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_property_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(null=True),
        ),
    ]
