# Generated by Django 5.1.6 on 2025-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_property_carpet_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
