# Generated by Django 5.1.6 on 2025-03-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_reigstermodel_id_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='userid',
        ),
    ]
