# Generated by Django 5.1.6 on 2025-03-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
