# Generated by Django 5.1.7 on 2025-03-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auctiontokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctiontokens',
            old_name='property',
            new_name='propertyid',
        ),
    ]
