# Generated by Django 5.1.7 on 2025-03-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_property_auctiontokens_propertyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiontokens',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
