# Generated by Django 5.1.7 on 2025-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_auctiontokens_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiontokens',
            name='price',
            field=models.FloatField(),
        ),
    ]
