# Generated by Django 5.1.6 on 2025-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_auctiontokens_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=50, null=True),
        ),
    ]
