# Generated by Django 5.1.6 on 2025-04-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactmodel',
        ),
    ]
