# Generated by Django 5.1.6 on 2025-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='security_deposit',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('1 month', '1 month'), ('2 month', '2 month'), ('Custom', 'Custom')], max_length=50, null=True),
        ),
    ]
